# Generated by Django 2.1.2 on 2018-11-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('writer', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('password', models.CharField(max_length=16)),
                ('viewCnt', models.IntegerField(default=0)),
                ('regTime', models.DateTimeField(auto_now_add=True)),
                ('updTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
